# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:16beta1-bullseye
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  server:
    build: server
    ports:
      - "9090:9090"
    # "зависит от",
    depends_on:
      - db
    # переменные окружения
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=shareit
      - DB_USER=test
      - DB_PASS=test
  gateway:
    build: gateway
    ports:
      - "8080:8080"
    # "зависит от",
    depends_on:
      - server